module Content
end
require_dependency 'content/course/course_command_handler.rb'
require_dependency 'content/course/course_created.rb'
require_dependency 'content/course/course_removed.rb'
require_dependency 'content/course/course_state.rb'
require_dependency 'content/course/course_title_set.rb'
require_dependency 'content/course/course.rb'
require_dependency 'content/course/create_course.rb'
require_dependency 'content/course/remove_course.rb'
require_dependency 'content/course/set_course_title.rb'

require_dependency 'content/deck/add_card_to_deck.rb'
require_dependency 'content/deck/card_added_to_deck.rb'
require_dependency 'content/deck/card_removed_from_deck.rb'
require_dependency 'content/deck/card.rb'
require_dependency 'content/deck/course_presence_validator.rb'
require_dependency 'content/deck/create_deck_in_course.rb'
require_dependency 'content/deck/deck_command_handler.rb'
require_dependency 'content/deck/deck_created_in_course.rb'
require_dependency 'content/deck/deck_removed.rb'
require_dependency 'content/deck/deck_state.rb'
require_dependency 'content/deck/deck_title_set.rb'
require_dependency 'content/deck/deck.rb'
require_dependency 'content/deck/remove_card_from_deck.rb'
require_dependency 'content/deck/remove_deck.rb'
require_dependency 'content/deck/set_deck_title.rb'


require_dependency 'content/read_models/courses/course.rb'
require_dependency 'content/read_models/courses/event_handler.rb'
require_dependency 'content/read_models/courses/read_model.rb'
